apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nowu-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JElgar/argo-test.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: nowu

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
