apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meilisearch
  namespace: meilisearch
spec:
  project: default
  source:
    repoURL: https://meilisearch.github.io/meilisearch-kubernetes
    targetRevision: 0.4.0
    chart: meilisearch/meilisearch
  destination:
    server: https://kubernetes.default.svc
    namespace: meilisearch

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
