apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 25.9.0
  releaseName: kube-prometheus-stack
  namespace: prometheus
